Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,9 +39,13 @@ jobs:
           echo "RUN_ID berhasil didapatkan: $RUN_ID"
           
       - name: Build Docker Model
+        continue-on-error: false  # Ubah ke true jika ingin pipeline lanjut meski gagal di langkah ini
         run: |
-          # Pastikan sintaks variabel env.RUN_ID rapat
-          mlflow models build-docker --model-uri "runs:/${{env.RUN_ID}}/model" --name "cc"
+          if [ -z "$RUN_ID" ]; then
+            echo "Error: RUN_ID tidak ditemukan!"
+            exit 1
+          fi
+          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
